### ISSUE TITLE
Resources are changed after a rebuild

### ISSUE THREAD

**Issue by Zenlua** [REAndroid/APKEditor#97]
Version: 1.3.7

+ When compressing some lost text, will it have any effect on the application?
![Screenshot_20240406-101654](https://github.com/REAndroid/APKEditor/assets/143571950/fc0ebc3f-b675-4598-8dc3-796dce250922)

+ When recompressing the data, the changes are small and not very important.
![Screenshot_20240406-160014](https://github.com/REAndroid/APKEditor/assets/143571950/eccd3348-44f3-4d5e-a61b-7ba8c3576262)

**Comment by REAndroid** [comment]
We can't reproduce this issue without the apk. The attr case needs further investigation.
On second dimen case the problem comes from java's float number division/multiplication accuracy, normally it is less than +/- 0.00005, for some reason if you want to keep original value you need to use json format

**Comment by Zenlua** [comment]
https://gofile.io/d/3pZ7xr

Here is the apk, thanks

**Comment by Zenlua** [comment]
Same issue, this is the last I know of, the tool is improving day by day.

![Screenshot_20240406-200634](https://github.com/REAndroid/APKEditor/assets/143571950/69ab2e75-baab-4a88-bfa9-a2b8243707f9)

File apk:
https://mega.nz/file/VNlwUYRA#1sJD4ZRy2bvWWd3OG8ZfjEH7jg5coBAypZAfiHwrhZE

**Comment by REAndroid** [comment]
I can't reproduce your issue, i did DECOMPILE -> COMPILE -> DECOMPILE , then the output is the same. How you did your comparison ?

**Comment by Zenlua** [comment]
Use apktool or another decoder to see, I use mt manager to compare resources.arsc

**Comment by REAndroid** [comment]
APKEditor is different from other tools our main goal is to produce editable files so that you can build it back correctly to working apk. Where as apktool intended to produce android  standard source code, check #51 .
`formats="reference|string|integer|bool|color|float|dimension|fraction"` is equivalent to `format=any` thus you are free to code it like `<attr name="__removed3" >`.

### Q: Why APKEditor is not stripping away `format=any` like other tools?

### A:
During encoding we don't rely/trust xml tag name. Some obfuscators may use different name `<abcd name="__removed3" >`, but we need to correctly identify the type of entry is `attribute`, `style` or `plural` therefore our logic is:
  - If element contains  `format="xxx"` -> encode it as `attribute`
  - If element contains `parent="xxx"` -> encode it as `style`
  - If element contains `quantity="xxx"` -> encode it as `plural`

**Comment by Zenlua** [comment]
Thank you for your explanation. Great tool. Wishing you a good life.
